version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "5000:5000"

  weather:
    build: 
      context: ./weather_api
    ports:
      - "5001:5001"
