# minikube start
# kubectl apply -f kubernetes.yaml
# kubectl port-forward svc/frontend 5000:5000

---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: frontend
    labels:
        app: frontend
spec:
    replicas: 3
    selector:
        matchLabels:
            app: frontend
    template:
        metadata:
            labels:
                app: frontend
        spec:
            containers:
                - name: frontend
                  image: alexmaccalman/frontend:frontend  
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: weatherapi
    labels:
        app: weatherapi
spec:
    replicas: 3
    selector:
        matchLabels:
            app: weatherapi
    template:
        metadata:
            labels:
                app: weatherapi
        spec:
            containers:
                - name: weatherapi
                  image: alexmaccalman/weather_api:weather_api
                  
---
apiVersion: v1
kind: Service
metadata:
    name: weatherapi
spec:
    selector:
        app: weatherapi
    ports:
        - protocol: TCP
          port: 50051
          targetPort: 50051
---
apiVersion: v1
kind: Service
metadata:
    name: frontend
spec:
    type: LoadBalancer
    selector:
        app: frontend
    ports:
        - protocol: TCP
          port: 5000
          targetPort: 5000